# alembic/versions/0001_initial_schema.py
#
# Initial schema migration.
# Creates all five tables and the `orderstatus` Postgres enum type.
#
# Tables created (in dependency order):
#   1. meals           — menu items
#   2. ingredients     — raw ingredients with stock levels
#   3. meal_ingredients — many-to-many: meals ↔ ingredients (with quantity_required)
#   4. orders          — customer orders with state machine status
#   5. order_items     — many-to-many: orders ↔ meals (with quantity)
#
# Written by hand (not autogenerated) because there is no live database
# in the current environment. Hand-written migrations are reviewed line-by-line
# and match the ORM models exactly.

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers — used by Alembic to chain migrations.
revision: str = "0001"
down_revision: str | None = None  # first migration, no parent
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and the orderstatus enum from scratch.

    Order of creation matters for foreign key constraints:
      - meals and ingredients have no FKs, so they come first.
      - meal_ingredients references both → created after both.
      - orders has no FKs → can follow in any order.
      - order_items references orders and meals → created last.
    """

    # ── 1. Create the orderstatus enum type ───────────────────────────────────
    # Must be created before the `orders` table that uses it.
    # The explicit name="orderstatus" matches the ORM definition in order.py.
    # Calling create() directly so it exists as a standalone Postgres type —
    # Alembic will not drop it automatically when we drop the orders table,
    # so downgrade() handles it explicitly.
    orderstatus_enum = postgresql.ENUM(
        "PENDING",
        "PREPARING",
        "READY",
        "FAILED",
        name="orderstatus",
        create_type=False,  # we call .create() manually below
    )
    orderstatus_enum.create(op.get_bind(), checkfirst=True)

    # ── 2. meals ──────────────────────────────────────────────────────────────
    # ORM source: src/models/meal.py — class Meal
    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "is_available",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    # ── 3. ingredients ────────────────────────────────────────────────────────
    # ORM source: src/models/ingredient.py — class Ingredient
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column(
            "stock_quantity",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    # ── 4. meal_ingredients ───────────────────────────────────────────────────
    # ORM source: src/models/meal_ingredient.py — class MealIngredient
    # Composite PK: (meal_id, ingredient_id)
    # Both FKs use ondelete="CASCADE" — if the meal or ingredient is deleted,
    # the association row is automatically removed.
    op.create_table(
        "meal_ingredients",
        sa.Column("meal_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column(
            "quantity_required",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("meal_id", "ingredient_id"),
    )

    # ── 5. orders ─────────────────────────────────────────────────────────────
    # ORM source: src/models/order.py — class Order
    # The status column uses the orderstatus enum type created above.
    # created_at and updated_at both default to now() at the database level.
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PREPARING",
                "READY",
                "FAILED",
                name="orderstatus",
                create_type=False,  # already created above
            ),
            nullable=False,
            server_default="PENDING",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── 6. order_items ────────────────────────────────────────────────────────
    # ORM source: src/models/order_item.py — class OrderItem
    # Composite PK: (order_id, meal_id)
    # order_id FK uses ondelete="CASCADE" — deleting an order removes its items.
    # meal_id FK uses ondelete="RESTRICT" — cannot delete a meal that has been
    # ordered (preserves order history integrity).
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("meal_id", sa.Integer(), nullable=False),
        sa.Column(
            "quantity",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("order_id", "meal_id"),
    )


def downgrade() -> None:
    """Drop all tables and the orderstatus enum in reverse dependency order.

    order_items and meal_ingredients reference other tables, so they must be
    dropped before the tables they reference. The orderstatus enum type is
    a standalone Postgres object — it must be explicitly dropped after the
    orders table that used it.
    """

    # Drop tables in reverse dependency order.
    # order_items → orders → meal_ingredients → meals → ingredients
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("meal_ingredients")
    op.drop_table("meals")
    op.drop_table("ingredients")

    # Drop the Postgres enum type.
    # Must happen after orders (which uses it) is dropped.
    orderstatus_enum = postgresql.ENUM(
        "PENDING",
        "PREPARING",
        "READY",
        "FAILED",
        name="orderstatus",
        create_type=False,
    )
    orderstatus_enum.drop(op.get_bind(), checkfirst=True)
